package com.dbkynd.discordallowlist.discord;

import com.dbkynd.discordallowlist.DiscordAllowList;
import com.dbkynd.discordallowlist.http.ImageDownloader;
import com.dbkynd.discordallowlist.http.WebRequest;
import com.dbkynd.discordallowlist.mojang.MojangJSON;
import net.dv8tion.jda.api.EmbedBuilder;
import net.dv8tion.jda.api.entities.MessageEmbed;
import net.dv8tion.jda.api.events.interaction.SlashCommandEvent;
import org.apache.logging.log4j.Logger;

public class AddMeCommandHandler {
  private static final Logger LOGGER = DiscordAllowList.LOGGER;
  private static WebRequest request= new WebRequest();

  public static void action(SlashCommandEvent event, String ign) {
    event.deferReply(true).queue();

    LOGGER.info(event.getName() + " issued a Discord Bot addme command: " + ign);

    // Get the user data from the Mojang API
    MojangJSON mojang = request.getMojangData(ign);

    // Tell the discord member we cannot find any data for the username they submitted
    if (mojang == null || mojang.getId() == null) {
      event.reply("Unable to get Mojang data for username **" + ign + "**.").setEphemeral(true).queue();
      return;
    }

    String thumbnail = "https://crafatar.com/renders/body/" + mojang.getId();
    // Try to download the image so that it's in craftatar's cache for when Discord asks for it to embed.
    // I think when discord tries to embed the image it doesn't wait for it to be generated by craftatar
    // like it would for a web client. And therefor even though the url is valid, Discord was not showing the thumbnail
    // reliably, but now seems to. :D
    ImageDownloader.main(thumbnail);

    // Save to database
    String tableName = DiscordAllowList.getTableName();
    try {
      if (DiscordAllowList.getSql().itemExists("DiscordID", event.getId(), tableName)) {
        DiscordAllowList.getSql().set("MinecraftName", mojang.getName().toLowerCase(), "DiscordID", "=", event.getId(), tableName);
        DiscordAllowList.getSql().set("UUID", mojang.getUUID(), "DiscordID", "=", event.getId(), tableName);
      } else {
        DiscordAllowList.getSql().update("INSERT INTO " + tableName + " (DiscordID,MinecraftName,UUID) VALUES (\'" + event.getId() + "\',\'" + mojang.getName().toLowerCase() + "\',\'" + mojang.getUUID().toString() + "\');");
      }
    } catch (Exception e) {
      e.printStackTrace();
      event.getChannel().sendMessage("There was an error updating the Minecraft user database with username **" + mojang.getName() + "**.").queue();
    }

  // Tell the Discord member that everything worked as expected!
    EmbedBuilder builder = new EmbedBuilder();
    builder.setDescription("```" + mojang.getName() + "```\nhas been added to the Minecraft user database!");
    builder.setThumbnail(thumbnail);
    builder.setColor(48640);
    MessageEmbed embed = builder.build();

    event.replyEmbeds(embed).queue();
  }
}
